AWSTemplateFormatVersion: 2010-09-09
Description: SmartBard CloudFront distribution Cloudformation Template

Parameters: 
  Environment:
    Default: test
    Description: Env Suffix for SMBD Cloudfront Distribution
    Type: String

Resources:
  CloudFrontOriginAccessControl:
    Type: AWS::CloudFront::OriginAccessControl
    Properties: 
      OriginAccessControlConfig:
        Description: Default Origin Access Control
        Name: !Sub smbd-oac${Environment}
        OriginAccessControlOriginType: s3
        SigningBehavior: always
        SigningProtocol: sigv4
  
  CloudFrontImagesOriginAccessControl:
    Type: AWS::CloudFront::OriginAccessControl
    Properties:
      OriginAccessControlConfig:
        Description: Images Origin Access Control
        Name: !Sub smbd-images-oac${Environment}
        OriginAccessControlOriginType: s3
        SigningBehavior: always
        SigningProtocol: sigv4

  CloudFrontDistribution:
    Type: "AWS::CloudFront::Distribution"
    Properties:
      DistributionConfig:
        ViewerCertificate:
          AcmCertificateArn: arn:aws:acm:us-east-1:013130384093:certificate/f44022ba-d0a6-40a7-b79e-0edb89655ada
          MinimumProtocolVersion: TLSv1.2_2021
          SslSupportMethod: sni-only
        Origins:
          - DomainName: !Sub smbd-bucket${Environment}.s3.us-east-1.amazonaws.com
            Id: "S3Origin"
            S3OriginConfig:
              OriginAccessIdentity: ''
            OriginAccessControlId: !GetAtt CloudFrontOriginAccessControl.Id
        Enabled: true
        DefaultCacheBehavior:
          TargetOriginId: "S3Origin"
          ForwardedValues:
            QueryString: false
          CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6
          ViewerProtocolPolicy: "redirect-to-https"
          AllowedMethods: 
            - GET
            - HEAD
            - OPTIONS
            - PUT
            - POST
            - PATCH
            - DELETE
          MinTTL: 0
        DefaultRootObject: "index.html"
        Comment: "CloudFront Distribution for SMBD S3 Bucket"
        PriceClass: "PriceClass_All"
        HttpVersion: http2and3
        IPV6Enabled: true
        Aliases:
          - !Sub smbd${Environment}.smartbard.durkin.app
  
  CloudFrontImagesDistribution:
    Type: "AWS::CloudFront::Distribution"
    Properties:
      DistributionConfig:
        ViewerCertificate: arn:aws:acm:us-east-1:013130384093:certificate/f44022ba-d0a6-40a7-b79e-0edb89655ada
        MinimumProtocolVersion: TLSv1.2_2021
        SslSupportMethod: sni-only
      Origins:
        - DomainName: !Sub smbd-images${Environment}.s3.us-east-1.amazonaws.com
          Id: "S3Origin"
          S3OriginConfig:
            OriginAccessIdentity: ''
          OriginAccessControlId: !GetAtt CloudFrontImagesOriginAccessControl.Id
      Enabled: true
      DefaultCacheBehavior:
        TargetOriginid: "S3Origin"
        ForwardedValues:
          QueryString: false
        CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6
        ViewerProtocolPolicy: "redirect-to-https"
        AllowedMethods: 
          - GET
          - HEAD
          - OPTIONS
          - PUT
          - POST
          - PATCH
          - DELETE
        MinTTL: 0
      DefaultRootObject: "index.html"
      Comment: "CloudFront Distribution for SMBD S3 Bucket"
      PriceClass: "PriceClass_All"
      HttpVersion: http2and3
      IPV6Enabled: true
      Aliases:
        - !Sub smbd-images${Environment}.smartbard.durkin.app