AWSTemplateFormatVersion: 2010-09-09
Description: SmartBard CloudFront distribution Cloudformation Template

Parameters: 
  Environment:
    Default: test
    Description: Env Suffix for SMBD Cloudfront Distribution
    Type: String

Resources:
  CloudFrontDistribution:
    Type: "AWS::CloudFront::Distribution"
    Properties:
      DistributionConfig:
        ViewerCertificate:
          AcmCertificateArn: arn:aws:acm:us-east-1:013130384093:certificate/f44022ba-d0a6-40a7-b79e-0edb89655ada
          SslSupportMethod: sni-only
        Origins:
          - DomainName: !Sub smbd-bucket${Environment}.s3.us-east-1.amazonaws.com
            Id: "S3Origin"
            CustomOriginConfig: 
              OriginProtocolPolicy: match-viewer
        Enabled: true
        DefaultCacheBehavior:
          TargetOriginId: "S3Origin"
          ForwardedValues:
            QueryString: false
          ViewerProtocolPolicy: "redirect-to-https"
          AllowedMethods: 
            - GET
            - HEAD
            - OPTIONS
            - PUT
            - POST
            - PATCH
            - DELETE
          MinTTL: 0
        DefaultRootObject: "index.html"
        Comment: "CloudFront distribution for example-bucket"
        PriceClass: "PriceClass_All"
        Aliases:
          - !Sub ${Environment}.smartbard.durkin.app
