AWSTemplateFormatVersion: 2010-09-09
Description: SmartBard CloudFront distribution Cloudformation Template

Parameters: 
  Environment:
    Default: test
    Description: Env Suffix for SMBD Cloudfront Distribution
    Type: String
  Certificate:
    Default: 'arn'
    Description: ARN of existing ACM certificate
    Type: String
  Domain:
    Default: 'durkin.app'
    Description: Domain name being used for app
    Type: String

Resources:
  CloudFrontOriginAccessControl:
    Type: AWS::CloudFront::OriginAccessControl
    Properties: 
      OriginAccessControlConfig:
        Description: Default Origin Access Control
        Name: !Sub smbd-oac${Environment}
        OriginAccessControlOriginType: s3
        SigningBehavior: always
        SigningProtocol: sigv4
  
  CloudFrontImagesOriginAccessControl:
    Type: AWS::CloudFront::OriginAccessControl
    Properties:
      OriginAccessControlConfig:
        Description: Images Origin Access Control
        Name: !Sub smbd-images-oac${Environment}
        OriginAccessControlOriginType: s3
        SigningBehavior: always
        SigningProtocol: sigv4

  CloudFrontDistribution:
    Type: "AWS::CloudFront::Distribution"
    Properties:
      DistributionConfig:
        ViewerCertificate:
          AcmCertificateArn: !Ref Certificate
          MinimumProtocolVersion: TLSv1.2_2021
          SslSupportMethod: sni-only
        Origins:
          - DomainName: !Sub smbd-bucket${Environment}.s3.us-east-1.amazonaws.com
            Id: "S3Origin"
            S3OriginConfig:
              OriginAccessIdentity: ''
            OriginAccessControlId: !GetAtt CloudFrontOriginAccessControl.Id
        Enabled: true
        DefaultCacheBehavior:
          TargetOriginId: "S3Origin"
          ForwardedValues:
            QueryString: false
          CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6
          ViewerProtocolPolicy: "redirect-to-https"
          AllowedMethods: 
            - GET
            - HEAD
            - OPTIONS
            - PUT
            - POST
            - PATCH
            - DELETE
          MinTTL: 0
        DefaultRootObject: "index.html"
        Comment: "CloudFront Distribution for SMBD S3 Bucket"
        PriceClass: "PriceClass_All"
        HttpVersion: http2and3
        IPV6Enabled: true
        CustomErrorResponses:
          - ErrorCachingMinTTL: 10
            ErrorCode: 403
            ResponseCode: 200
            ResponsePagePath: /index.html
        Aliases:
          - !Sub smbd${Environment}.smartbard.${Domain}
  
  CloudFrontImagesDistribution:
    Type: "AWS::CloudFront::Distribution"
    Properties:
      DistributionConfig:
        ViewerCertificate:
          AcmCertificateArn: !Ref Certificate
          MinimumProtocolVersion: TLSv1.2_2021
          SslSupportMethod: sni-only
        Origins:
          - DomainName: !Sub smbd-images${Environment}.s3.us-east-1.amazonaws.com
            Id: "S3Origin"
            S3OriginConfig:
              OriginAccessIdentity: ''
            OriginAccessControlId: !GetAtt CloudFrontImagesOriginAccessControl.Id
        Enabled: true
        DefaultCacheBehavior:
          TargetOriginId: "S3Origin"
          ForwardedValues:
            QueryString: false
          CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6
          ViewerProtocolPolicy: "redirect-to-https"
          AllowedMethods: 
            - GET
            - HEAD
            - OPTIONS
            - PUT
            - POST
            - PATCH
            - DELETE
          MinTTL: 0
        DefaultRootObject: "index.html"
        Comment: "CloudFront Distribution for SMBD S3 Bucket"
        PriceClass: "PriceClass_All"
        HttpVersion: http2and3
        IPV6Enabled: true
        Aliases:
          - !Sub smbd-images${Environment}.smartbard.${Domain}

  S3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket:
        Fn::ImportValue: !Sub S3AppBucketArn${Environment}
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: "AllowCloudFrontServicePrincipal"
            Effect: "Allow"
            Principal:
              Service: "cloudfront.amazonaws.com"
            Action:
              - "s3:GetObject"
              - "s3:PutObject"
              - "s3:DeleteObject"
              - "s3:List*"
            Resource: !Sub "arn:aws:s3:::smbd-bucket${Environment}/*"
            Condition:
              StringEquals:
                AWS:SourceArn: !Join
                                 - ''
                                 - - 'arn:aws:cloudfront::013130384093:distribution/'
                                   - !Ref CloudFrontDistribution

  S3ImagesBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket:
        Fn::ImportValue: !Sub S3ImagesBucketArn${Environment}
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: "AllowCloudFrontServicePrincipal"
            Effect: "Allow"
            Principal:
              Service: "cloudfront.amazonaws.com"
            Action:
              - "s3:GetObject"
              - "s3:PutObject"
              - "s3:DeleteObject"
              - "s3:List*"
            Resource: !Sub "arn:aws:s3:::smbd-images${Environment}/*"
            Condition:
              StringEquals:
                AWS:SourceArn: !Join
                                 - ''
                                 - - 'arn:aws:cloudfront::013130384093:distribution/'
                                   - !Ref CloudFrontImagesDistribution
