AWSTemplateFormatVersion: 2010-09-09
Description: SmartBard CloudFront distribution Cloudformation Template

Parameters: 
  Environment:
    Default: test
    Description: Env Suffix for SMBD Cloudfront Distribution
    Type: String

Resources:
  CloudFrontOriginAccessIdentity:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: "OAI for CloudFront Distribution"
  CloudFrontDistribution:
    Type: "AWS::CloudFront::Distribution"
    Properties:
      DistributionConfig:
        ViewerCertificate:
          AcmCertificateArn: arn:aws:acm:us-east-1:013130384093:certificate/f44022ba-d0a6-40a7-b79e-0edb89655ada
          MinimumProtocolVersion: TLSv1.2_2021
          SslSupportMethod: sni-only
        Origins:
          - DomainName: !Sub smbd-bucket${Environment}.s3.us-east-1.amazonaws.com
            Id: "S3Origin"
            S3OriginConfig:
              OriginAccessIdentity:
                Fn::Join:
                  - ""
                  - - "origin-access-identity/cloudfront/"
                    - !Ref CloudFrontOriginAccessIdentity
        Enabled: true
        DefaultCacheBehavior:
          TargetOriginId: "S3Origin"
          ForwardedValues:
            QueryString: false
          CachePolicyId: CachingOptimized
          ViewerProtocolPolicy: "redirect-to-https"
          AllowedMethods: 
            - GET
            - HEAD
            - OPTIONS
            - PUT
            - POST
            - PATCH
            - DELETE
          MinTTL: 0
        DefaultRootObject: "index.html"
        Comment: "CloudFront distribution for SMBD S3 Bucket"
        PriceClass: "PriceClass_All"
        HttpVersion: http2and3
        IPV6Enabled: true
        Aliases:
          - !Sub smbd${Environment}.smartbard.durkin.app

Outputs:
  DistributionId:
    Description: CloudFront Distribution ID
    Value: !Ref CloudFrontDistribution