AWSTemplateFormatVersion: 2010-09-09
Description: SmartBard Database Cloudformation Template
Parameters: 
  Environment:
    Default: test
    Description: Env Suffix for SMBD Bucket
    Type: String

  DBUser:
    Default: smartbarduser
    Description: The database admin account username
    Type: String
    MinLength: '1'
    MaxLength: '16'
    AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'
    ConstraintDescription: Alphanumeric characters

  DBPassword:
    Default: smartbarduser
    Description: The database admin account password (will need to decide where to store pwd for security later)
    Type: String
    MinLength: '1'
    MaxLength: '41'
    AllowedPattern: '[a-zA-Z0-9]+'
    ConstraintDescription: Alphanumeric characters

Resources: 
  DBSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Allow access to database instance
      VpcId:         
        Fn::ImportValue:
          !Sub "VPC${Environment}"
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 5432
          ToPort: 5432
          CidrIp: 0.0.0.0/0

  DBSubnetGroup:
    Type: 'AWS::RDS::DBSubnetGroup'
    Properties:
      DBSubnetGroupDescription: Database subnet group
      SubnetIds:
        - Fn::ImportValue:
            !Sub "SubnetA${Environment}"
        - Fn::ImportValue:
            !Sub "SubnetB${Environment}"

  rdsDBInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      AllocatedStorage: 100
      DBInstanceClass: db.t3.micro
      DBSubnetGroupName: !Ref DBSubnetGroup
      AvailabilityZone: us-east-1b
      BackupRetentionPeriod: 7
      Engine: postgres
      EngineVersion: 14.5
      MasterUsername: !Ref DBUser
      MasterUserPassword: !Ref DBPassword
      MultiAZ: false
      Port: 5432
      PubliclyAccessible: true
      StorageEncrypted: true
      VPCSecurityGroups:        
        - !Ref DBSecurityGroup
    DeletionPolicy: Snapshot
