AWSTemplateFormatVersion: 2010-09-09
Description: SmartBard Database Cloudformation Template
Parameters: 
  DBUser:
    Default: postgres
    Description: The database admin account username
    Type: String
    MinLength: '1'
    MaxLength: '16'
    AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'
    ConstraintDescription: Alphanumeric characters

  DBPassword:
    Default: postgres
    Description: The database admin account password (will need to decide where to store pwd for security later)
    Type: String
    MinLength: '1'
    MaxLength: '41'
    AllowedPattern: '[a-zA-Z0-9]+'
    ConstraintDescription: Alphanumeric characters

Resources: 
  rdsDBInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      AllocatedStorage: 100
      DBInstanceClass: db.t3.micro
      AvailabilityZone: us-east-1
      BackupRetentionPeriod: 7
      Engine: postgres
      EngineVersion: 14.5
      MasterUsername: !Ref DBUser
      MasterUserPassword: !Ref DBPassword
      MultiAZ: false
      Port: 5432
      PubliclyAccessible: false
      StorageEncrypted: true
    DeletionPolicy: Snapshot
