AWSTemplateFormatVersion: 2010-09-09
Description: SmartBard Database Cloudformation Template
Parameters: 
  Environment:
    Default: test
    Description: Env Suffix for SMBD Bucket
    Type: String

Resources:
  DBUsername:
    Type: 'AWS::SecretsManager::Secret'
    Properties:
      Description: Username for DB
      GenerateSecretString:
        ExcludePunctuation: true
        IncludeSpace: false
        PasswordLength: 16
      Name: db-username
  
  DBPassword:
    Type: 'AWS::SecretsManager::Secret'
    Properties:
      Description: Password for DB
      GenerateSecretString:
        IncludeSpace: false
        PasswordLength: 32
      Name: db-password
 
  DBSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Allow access to database instance
      VpcId:         
        Fn::ImportValue:
          !Sub "VPC${Environment}"
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 5432
          ToPort: 5432
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: !Sub smbd-db-security-group${Environment}


  DBSubnetGroup:
    Type: 'AWS::RDS::DBSubnetGroup'
    Properties:
      DBSubnetGroupDescription: Database subnet group
      SubnetIds:
        - Fn::ImportValue:
            !Sub "SubnetA${Environment}"
        - Fn::ImportValue:
            !Sub "SubnetB${Environment}"
      Tags:
        - Key: Name
          Value: !Sub smbd-db-subnet-group${Environment}

  DBInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      AllocatedStorage: 100
      DBInstanceClass: db.t3.micro
      DBSubnetGroupName: !Ref DBSubnetGroup
      AvailabilityZone: us-east-1b
      BackupRetentionPeriod: 7
      Engine: postgres
      EngineVersion: 14.5
      MasterUsername: '{{resolve:secretsmanager:db-username:SecretString}}'
      MasterUserPassword: '{{resolve:secretsmanager:db-password:SecretString}}'
      MultiAZ: false
      Port: 5432
      PubliclyAccessible: true
      StorageEncrypted: true
      VPCSecurityGroups:        
        - !Ref DBSecurityGroup
    DeletionPolicy: Snapshot

  DBHostname:
    Type: 'AWS::SecretsManager::Secret'
    Properties:
      Description: Hostname for DB
      SecretString: !GetAtt DBInstance.Endpoint.Address
      Name: db-hostname
