AWSTemplateFormatVersion: 2010-09-09
Description: SmartBard EC2 Cloudformation Template

Parameters: 
  Environment:
    Default: test
    Description: Env Suffix for SMBD EC2 Server
    Type: String

Resources: 
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0ff8a91507f77f867
      InstanceType: t3.small
      Monitoring: true
      SecurityGroupIds:
        - Fn::ImportValue:
            !Sub "DefaultSecurityGroup${Environment}"
      SubnetId:
        Fn::ImportValue:
          !Sub "SubnetA${Environment}"
      Tags:
        - Key: Name
          Value: !Sub smbd-ec2${Environment}

  LoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties: 
      IpAddressType: dualstack
      Name: !Sub smbd-load-balancer${Environment}
      Scheme: internet-facing
      SecurityGroups: 
        - Fn::ImportValue:
            !Sub "DefaultSecurityGroup${Environment}"
      Subnets: 
        - Fn::ImportValue:
            !Sub "SubnetA${Environment}"
        - Fn::ImportValue:
            !Sub "SubnetB${Environment}"
      Type: application
