AWSTemplateFormatVersion: 2010-09-09
Description: SmartBard EC2 Cloudformation Template

Parameters: 
  Environment:
    Default: test
    Description: Env Suffix for SMBD IAM Role
    Type: String

Resources: 
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0ff8a91507f77f867
      InstanceType: t3.small
      Monitoring: true
      SecurityGroupIds:
        Fn::ImportValue:
          !Sub "DefaultSecurityGroup${Environment}"
      SubnetId:
        Fn::ImportValue:
          !Sub "SubnetA${Environment}"
