AWSTemplateFormatVersion: 2010-09-09
Description: SmartBard EC2 Cloudformation Template

Parameters: 
  Environment:
    Default: test
    Description: Env Suffix for SMBD EC2 Server
    Type: String

Resources: 
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0ff8a91507f77f867
      InstanceType: t3.small
      Monitoring: true
      SecurityGroupIds:
        - Fn::ImportValue:
            !Sub "DefaultSecurityGroup${Environment}"
      SubnetId:
        Fn::ImportValue:
          !Sub "SubnetA${Environment}"
      Tags:
        - Key: Name
          Value: !Sub smbd-ec2${Environment}
    Metadata:
      AWS::CloudFormation::StackPolicy:
        Statement:
        - Effect: Allow
          Action:
            - Update:*
            - CloudFormation:ContinueUpdateRollback
            - CloudFormation:UpdateStack
          Principal: "*"
          Resource: "*"
          Condition:
            StringEquals:
              CloudFormation:StackStatus:
                - UPDATE_ROLLBACK_COMPLETE
                - UPDATE_ROLLBACK_FAILED

