AWSTemplateFormatVersion: 2010-09-09
Description: SmartBard EC2 Cloudformation Template

Parameters: 
  Environment:
    Default: test
    Description: Env Suffix for SMBD EC2 Server
    Type: String

Resources: 
  KeyPair:
    Type: AWS::EC2::KeyPair
    Properties: 
      KeyName: !Sub smbd-keypair${Environment}
      KeyType: rsa

  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0ff8a91507f77f867
      KeyName: !Ref KeyPair
      InstanceType: t3.small
      Monitoring: true
      SecurityGroupIds:
        - Fn::ImportValue:
            !Sub "DefaultSecurityGroup${Environment}"
      SubnetId:
        Fn::ImportValue:
          !Sub "SubnetA${Environment}"
      Tags:
        - Key: Name
          Value: !Sub smbd-ec2${Environment}

  LoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties: 
      IpAddressType: ipv4
      Name: !Sub smbd-load-balancer${Environment}
      Scheme: internet-facing
      SecurityGroups: 
        - Fn::ImportValue:
            !Sub "DefaultSecurityGroup${Environment}"
      Subnets: 
        - Fn::ImportValue:
            !Sub "SubnetA${Environment}"
        - Fn::ImportValue:
            !Sub "SubnetB${Environment}"
      Type: application

  TargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: !Sub smbd-target-group${Environment}
      Protocol: HTTPS
      Port: 3000
      VpcId:
        Fn::ImportValue:
            !Sub "VPC${Environment}"
      TargetType: instance

  LoadBalancerListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref TargetGroup
      LoadBalancerArn: !Ref LoadBalancer
      Port: 3000
      Protocol: HTTPS
      SslPolicy: ELBSecurityPolicy-2016-08
      Certificates:
        - CertificateArn: arn:aws:acm:us-east-1:013130384093:certificate/f44022ba-d0a6-40a7-b79e-0edb89655ada

Outputs:
  KeyFingerprint:
    Description: The EC2 fingerprint
    Value: !GetAtt KeyPair.KeyFingerprint
  
  KeyPairId:
    Description: The keypair id
    Value: !GetAtt KeyPair.KeyPairId
  