AWSTemplateFormatVersion: 2010-09-09
Description: SmartBard EC2 Cloudformation Template

Resources: 
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: false
      EnableDnsHostnames: false
      InstanceTenancy: default

  Subnet:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: us-east-1
      VpcId: !GetAtt VPC.VpcID
      CidrBlock: 10.0.0.0/16

  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0ff8a91507f77f867
      InstanceType: t3.small
      Monitoring: true
      SecurityGroupIds:
        - !GetAtt VPC.DefaultSecurityGroup