AWSTemplateFormatVersion: 2010-09-09
Description: SmartBard IAM Role Cloudformation Template

Parameters: 
  IAMRoleName: 
    Description: General IAM Role for SmartBard
    Type: String
    Default: smbd-iam
Resources: 
  IAM Role:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Ref IAMRoleName
      AssumeRolePolicyDocument: 
      Policies:
        - 
         PolicyName: "root"
         PolicyDocument:
           Version: "2012-10-17"
           Statement:
              - 
                Effect: "Allow"
                Action: "*"
                Resource: "*"