AWSTemplateFormatVersion: 2010-09-09
Description: SmartBard S3 Cloudformation Template

Parameters: 
  Environment:
    Default: test
    Description: Env Suffix for SMBD Bucket
    Type: String

Resources: 
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties: 
      AccessControl: Private
      BucketName: !Sub smbd-bucket${Environment}
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
              
  S3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Sub smbd-bucket${Environment}
      PolicyDocument: 
        Version: 2012-10-17
        Statement:
          - Action:
              - 's3:GetObject'
              - 's3:PutObject'
              - 's3:List*'
            Effect: Allow
            Resource: 
              - !Sub "arn:aws:s3:::smbd-bucket${Environment}/*"
            Principal: '*'
