AWSTemplateFormatVersion: 2010-09-09
Description: SmartBard S3 Cloudformation Template

Parameters: 
  Environment:
    Default: test
    Description: Env Suffix for SMBD Bucket
    Type: String

Resources: 
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties: 
      AccessControl: Private
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
      BucketName: !Sub smbd-bucket${Environment}
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
  
  S3ImagesBucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: Private
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
      BucketName: !Sub smbd-images${Environment}
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256

  S3AccessPoint:
    Type: AWS::S3::AccessPoint
    Properties:
      Bucket: !Ref S3ImagesBucket
      Name: !Sub smbd-images-ap${Environment}
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false

Outputs:
  S3AppBucketArn:
    Description: ARN of S3 bucket for app
    Value: !Ref S3Bucket
    Export:
      Name: !Sub S3AppBucketArn${Environment}

  S3ImagesBucketArn:
    Description: ARN of S3 bucket for assets
    Value: !Ref S3ImagesBucket
    Export:
      Name: !Sub S3ImagesBucketArn${Environment}
