AWSTemplateFormatVersion: 2010-09-09
Description: SmartBard S3 Cloudformation Template

Parameters: 
  BucketName: 
    Default: smbd-s3
    Description: Bucket Storing SmartBard Announcement and User Data
    Type: String

Resources: 
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties: 
      AccessControl: Private
      BucketName: 
        Ref: BucketName
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
              
  S3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: 
        Ref: S3Bucket
      PolicyDocument: 
        Version: 2012-10-17
        Statement:
          - Action:
              - 's3:GetObject'
              - 's3:PutObject'
              - 's3:ListObjectsV2'
            Effect: Allow
            Resource: 
              - '*'
            Principal: 
              - AWS: 
                - '*'
