AWSTemplateFormatVersion: '2010-09-09'
Description: SmartBard VPC Cloudformation Template

Parameters: 
  Environment:
    Default: testt
    Description: Env Suffix for SMBD VPC Group
    Type: String

Resources:
  VPC:
    Type: 'AWS::EC2::VPC'
    Properties:
      CidrBlock: '10.0.0.0/16'
      Tags:
        - Key: Name
          Value: !Sub smbd-vpc${Environment}

  SubnetA:
    Type: 'AWS::EC2::Subnet'
    Properties:
      VpcId: !Ref VPC
      CidrBlock: '10.0.1.0/24'
      AvailabilityZone: us-east-1a
      Tags:
        - Key: Name
          Value: !Sub smbd-subneta${Environment}

  SubnetB:
    Type: 'AWS::EC2::Subnet'
    Properties:
      VpcId: !Ref VPC
      CidrBlock: '10.0.2.0/24'
      AvailabilityZone: us-east-1b
      Tags:
        - Key: Name
          Value: !Sub smbd-subnetb${Environment}

  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: !Sub smbd-internet-gateway${Environment}

  InternetGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      InternetGatewayId: !Ref InternetGateway
      VpcId: !Ref VPC

  RouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: !Sub smbd-route-table${Environment}

  DefaultRoute:
    Type: AWS::EC2::Route
    DependsOn: InternetGatewayAttachment
    Properties:
      RouteTableId: !Ref RouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway

  SubnetARouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref RouteTable
      SubnetId: !Ref SubnetA

  SubnetBRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref RouteTable
      SubnetId: !Ref SubnetB

Outputs:
  VPC:
    Description: A reference to the created VPC
    Value: !Ref VPC
    Export:
      Name: !Sub VPC${Environment}

  SubnetA:
    Description: A reference to the subnet in the 1st Availability Zone
    Value: !Ref SubnetA
    Export:
      Name: !Sub SubnetA${Environment}

  SubnetB:
    Description: A reference to the subnet in the 2nd Availability Zone
    Value: !Ref SubnetB
    Export:
      Name: !Sub SubnetB${Environment}
