name: Deploy S3 Cloudformation Stack

on:
  push:
    paths:
      - 'cfn-stacks/s3.yaml'

  workflow_dispatch:
    inputs:
      region:
        description: 'AWS Region to deploy to'
        required: true
        default: 'us-east-1'


jobs:
  s3-cfn-deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Configure AWS credentials
        id: creds
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: "us-east-1"

      - name: Deploy S3 Buckets CloudFormation Stacks
        id: s3-bucket
        uses: aws-actions/aws-cloudformation-github-deploy@v1.0.3
        with:
          name: S3Bucket
          template: cfn-stacks/s3.yaml