name: PROD - Deploy IAM Cloudformation Stack

on:
  workflow_dispatch:
    inputs:
      region:
        description: 'AWS Region to deploy to'
        required: true
        default: 'us-east-1'

jobs:
  iam-cfn-prod-deployment:
    runs-on: ubuntu-latest
    environment: Prod
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Configure AWS credentials
        id: creds
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: "us-east-1"

      - name: Deploy IAM Roles CloudFormation Stack
        id: iam-role
        uses: aws-actions/aws-cloudformation-github-deploy@v1.0.3 
        with:
          name: smbd-iam-prod
          template: cfn-stacks/iam.yaml
          parameter-overrides: "Environment=-prod"
          no-fail-on-empty-changeset: "1"
